siderolabs/extensions

- .drone.yaml
- Makefile
- Pkgfile
- base/pkg.yaml
- gvisor/gvisor.part
- gvisor/manifest.yaml
- gvisor/pkg.yaml
- musl/pkg.yaml
Signed-off-by: Andrew Rynhard <andrew@rynhard.io>
> feat: add gvisor

- intel-ucode/manifest.yaml
We don't have Talos 1.0 yet ;)
> chore: fix version requirement for intel-ucode

- Makefile
- Pkgfile
- amd-ucode/manifest.yaml
- amd-ucode/pkg.yaml
This PR adds the amd extension from our linux-firmware pkg.
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>
> feat: add amd-ucode extension

- intel-ucode/manifest.yaml
- intel-ucode/pkg.yaml
See https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20220207
> feat: update intel microcode to 20220207

- Makefile
- Pkgfile
- README.md
- container-runtime/gvisor/README.md
- container-runtime/gvisor/runsc.toml
- examples/hello-world-service/README.md
- examples/hello-world-service/src/go.mod
- nvidia-container-toolkit/DEVELOPMENT.md
- nvidia-container-toolkit/README.md
- nvidia-container-toolkit/glibc/ld.so.conf
- nvidia-container-toolkit/glibc/pkg.yaml
- nvidia-container-toolkit/manifest.yaml
- nvidia-container-toolkit/nvidia-container-cli/patches/libnvidia-container/Makefile.patch
- nvidia-container-toolkit/nvidia-container-cli/patches/libnvidia-container/common.h.patch
- nvidia-container-toolkit/nvidia-container-cli/patches/libnvidia-container/nvc_ldcache.c.patch
- nvidia-container-toolkit/nvidia-container-cli/pkg.yaml
- nvidia-container-toolkit/nvidia-container-runtime/nvidia-container-runtime.part
- nvidia-container-toolkit/nvidia-container-runtime/nvidia-container-runtime.toml
- nvidia-container-toolkit/nvidia-container-runtime/patches/nvidia-container-runtime/main.go.patch
- nvidia-container-toolkit/nvidia-container-runtime/patches/nvidia-container-toolkit/hook_config.go.patch
- nvidia-container-toolkit/nvidia-container-runtime/pkg.yaml
- nvidia-container-toolkit/nvidia-device-create/15-nvidia-device.rules
- nvidia-container-toolkit/nvidia-device-create/patches/nvidia-graphics-drivers-build/Makefile.patch
- nvidia-container-toolkit/nvidia-device-create/pkg.yaml
- nvidia-container-toolkit/nvidia-pkgs/pkg.yaml
- nvidia-container-toolkit/pkg.yaml
Add required components for nvidia container toolkit
> Nvidia container runtime

- README.md
This is a temporary solution until we get a real registry.
> docs: provide a minimal extension catalog

- CHANGELOG.md
- hack/release.sh
- hack/release.toml
This is the official v1.0.0 release.
> release(v1.0.0): prepare release

- Pkgfile
In preparation for Talos 1.1.0-beta.
> chore: update pkgs to 1.1.0

- README.md
Allow modules to be loaded via extensions.
> feat: allow modules to be loaded via extension

- .github/renovate.json
- container-runtime/vars.yaml
- firmware/vars.yaml
- nvidia-gpu/vars.yaml
> chore: fix regex for `vars.yaml`

- Pkgfile
This is the official v1.2.0 release.
> release(v1.2.0): prepare release

- CHANGELOG.md
- hack/release.toml
Fix CHANGELOG not being updated on last release.
> chore: fix changelog

- CHANGELOG.md
- Pkgfile
- hack/release.toml
This is the official v1.2.1 release.
> release(v1.2.1): prepare release

- .drone.yaml
- CHANGELOG.md
- Makefile
- Pkgfile
- hack/release.sh
- hack/release.toml
This is the official v1.2.2 release.
> release(v1.2.2): prepare release

- hack/release.sh
> chore: fix release script

- .drone.yaml
Add a docker service fo creating release notes.
> fix: drone release pipeline

- CHANGELOG.md
- Pkgfile
- hack/release.toml
This is the official v1.2.3 release.
> release(v1.2.3): prepare release

- .drone.yaml
- Makefile
- Pkgfile
- container-runtime/gvisor/pkg.yaml
- container-runtime/vars.yaml
- hack/release.toml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime/patches/nvidia-container-toolkit/hook_config.go.patch
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.sum
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced.yaml
- nvidia-gpu/vars.yaml
- power/nut-client/pkg.yaml
- storage/iscsi-tools/iscsid-wrapper/go.mod
- storage/iscsi-tools/iscsid-wrapper/go.sum
- storage/iscsi-tools/open-iscsi/pkg.yaml
- storage/iscsi-tools/open-isns/pkg.yaml
- storage/iscsi-tools/vars.yaml
> chore: bump deps

- CHANGELOG.md
- Pkgfile
- hack/release.toml
This is the official v1.2.4 release.
> release(v1.2.4): prepare release

- CHANGELOG.md
- Pkgfile
- hack/release.toml
This is the official v1.2.5 release.
> release(v1.2.5): prepare release

- Makefile
- Pkgfile
- README.md
- hack/release.toml
- storage/drbd/manifest.yaml
- storage/drbd/pkg.yaml
- storage/drbd/vars.yaml
Extension for pkg created in this PR: https://github.com/siderolabs/pkgs/pull/571
> feat: add 'drbd' extension

- CHANGELOG.md
- Pkgfile
- README.md
This is the official v1.3.0-alpha.1 release.
> release(v1.3.0-alpha.1): prepare release

- CHANGELOG.md
- Pkgfile
- hack/release.toml
This is the official v1.2.7 release.
> release(v1.2.7): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v1.3.0-beta.0 release.
> release(v1.3.0-beta.0): prepare release

- hack/release.toml
- storage/iscsi-tools/pkg.yaml
- storage/iscsi-tools/vars.yaml
> fix: iscsi-tools paths

- CHANGELOG.md
- Pkgfile
- hack/release.toml
This is the official v1.3.0-beta.2 release.
> release(v1.3.0-beta.2): prepare release

- CHANGELOG.md
- Pkgfile
- hack/release.toml
This is the official v1.3.0 release.
> release(v1.3.0): prepare release

- CHANGELOG.md
- Pkgfile
- hack/release.toml
This is the official v1.2.8 release.
> release(v1.2.8): prepare release

- CHANGELOG.md
- Pkgfile
- hack/release.toml
This is the official v1.3.1 release.
> release(v1.3.1): prepare release

- CHANGELOG.md
- Makefile
- Pkgfile
- hack/release.toml
This is the official v1.3.2 release.
> release(v1.3.2): prepare release

- Pkgfile
- container-runtime/gvisor/pkg.yaml
- container-runtime/vars.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.sum
- nvidia-gpu/vars.yaml
- storage/iscsi-tools/iscsid-wrapper/go.mod
- storage/iscsi-tools/iscsid-wrapper/go.sum
Bump pkgs version and the dependencies.
Signed-off-by: Utku Ozdemir <utku.ozdemir@siderolabs.com>
> chore: bump dependencies

- CHANGELOG.md
- Pkgfile
- hack/release.toml
This is the official v1.3.3 release.
> release(v1.3.3): prepare release

- CHANGELOG.md
- Pkgfile
- hack/release.toml
This is the official v1.4.0-alpha.1 release.
> release(v1.4.0-alpha.1): prepare release

- .github/renovate.json
- Makefile
- Pkgfile
- container-runtime/gvisor/pkg.yaml
- container-runtime/vars.yaml
- firmware/intel-ucode/pkg.yaml
- firmware/vars.yaml
- hack/release.toml
- nvidia-gpu/nvidia-container-toolkit/glibc/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime/nvidia-container-runtime.toml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-pkgs/pkg.yaml
- nvidia-gpu/nvidia-fabricmanager/pkg.yaml
- nvidia-gpu/vars.yaml
Chore/bump deps+renovate cleanup
> chore: bump deps+renovate cleanup

- CHANGELOG.md
- Pkgfile
- hack/release.toml
This is the official v1.3.5 release.
> release(v1.3.5): prepare release

- .drone.yaml
> fix: drone artifact path

- .drone.yaml
- Makefile
- drivers/gasket/pkg.yaml
- drivers/mellanox-ofed/pkg.yaml
- firmware/amd-ucode/pkg.yaml
- firmware/bnx2-bnx2x/pkg.yaml
- firmware/i915-ucode/pkg.yaml
- internal/base/pkg.yaml
- nvidia-gpu/nvidia-modules/pkg.yaml
- power/nut-client/pkg.yaml
- storage/drbd/pkg.yaml
- storage/iscsi-tools/open-iscsi/pkg.yaml
- storage/iscsi-tools/open-isns/pkg.yaml
Use standard `PKGS` variable.
Also rename `deps` to `extensions-metadata` to be more clear.
> chore: use standard `PKGS` variable

- CHANGELOG.md
This is the official v1.4.0-alpha.2 release.
> release(v1.4.0-alpha.2): prepare release

- Makefile
- hack/release.toml
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.sum
- nvidia-gpu/nvidia-container-toolkit/nvidia-pkgs/pkg.yaml
- nvidia-gpu/vars.yaml
- storage/iscsi-tools/iscsid-wrapper/go.mod
- storage/iscsi-tools/iscsid-wrapper/go.sum
Bump NVIDIA following pkgs version.
> feat: update Go 1.20.2

- CHANGELOG.md
- Pkgfile
- hack/release.toml
This is the official v1.3.6 release.
> release(v1.3.6): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v1.4.0-alpha.3 release.
> release(v1.4.0-alpha.3): prepare release

- CHANGELOG.md
- Makefile
This is the official v1.4.0-alpha.4 release.
> release(v1.4.0-alpha.4): prepare release

- CHANGELOG.md
- Makefile
This is the official v1.4.0-beta.0 release.
> release(v1.4.0-beta.0): prepare release

- CHANGELOG.md
- Pkgfile
- hack/release.toml
This is the official v1.3.7 release.
> release(v1.3.7): prepare release

- CHANGELOG.md
- Makefile
- hack/release.toml
This is the official v1.4.0 release.
> release(v1.4.0): prepare release

- CHANGELOG.md
- Makefile
- hack/release.toml
This is the official v1.4.1 release.
> release(v1.4.1): prepare release

- CHANGELOG.md
- Makefile
- hack/release.toml
This is the official v1.4.2 release.
> release(v1.4.2): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v1.4.3 release.
> release(v1.4.3): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v1.4.4 release.
> release(v1.4.4): prepare release

- CHANGELOG.md
This is the official v1.4.4 release.
> re-release(v1.4.4): prepare release

- CHANGELOG.md
- Makefile
- Pkgfile
- firmware/intel-ucode/pkg.yaml
- firmware/vars.yaml
- hack/release.toml
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.sum
- nvidia-gpu/vars.yaml
- storage/iscsi-tools/iscsid-wrapper/go.mod
- storage/iscsi-tools/iscsid-wrapper/go.sum
- storage/iscsi-tools/tgt/pkg.yaml
This is the official v1.5.0-alpha.0 release.
> release(v1.5.0-alpha.0): prepare release

- CHANGELOG.md
- Makefile
This is the official v1.4.5 release.
> release(v1.4.5): prepare release

- CHANGELOG.md
This is the official v1.5.0-alpha.1 release.
> release(v1.5.0-alpha.1): prepare release

- .drone.yaml
This fixes blob upload when the pipeline is triggered multiple times.
> fix: ci blob upload

- CHANGELOG.md
- Makefile
This is the official v1.5.0-alpha.2 release.
> release(v1.5.0-alpha.2): prepare release

- CHANGELOG.md
This is the official v1.5.0-alpha.3 release.
> release(v1.5.0-alpha.3): prepare release

- CHANGELOG.md
- Makefile
- hack/release.toml
This is the official v1.4.7 release.
> release(v1.4.7): prepare release

- network/tailscale/README.md
use list to highlight env vars
> fix(docs): readability for Tailscale docs

- CHANGELOG.md
- hack/release.toml
This is the official v1.5.0-beta.1 release.
> release(v1.5.0-beta.1): prepare release

- .drone.yaml
- CHANGELOG.md
- hack/release.toml
This is the official v1.5.0 release.
> release(v1.5.0): prepare release

- hack/release.toml
- storage/btrfs/manifest.yaml
> fix: btrfs extension constraint

- CHANGELOG.md
- Makefile
- hack/release.toml
This is the official v1.5.1 release.
> release(v1.5.1): prepare release

- CHANGELOG.md
- Makefile
This is the official v1.6.0-alpha.0 release.
> release(v1.6.0-alpha.0): prepare release

- Makefile
- hack/release.toml
This is the official v1.5.2 release.
> release(v1.5.2): prepare release

- Makefile
- README.md
- hack/release.toml
- misc/binfmt-misc/README.md
- misc/binfmt-misc/files/modules.txt
- misc/binfmt-misc/manifest.yaml
- misc/binfmt-misc/pkg.yaml
- misc/binfmt-misc/vars.yaml
Add binfmt-misc kernel support.
https://github.com/siderolabs/pkgs/pull/804
> feat: add binfmt_misc

- CHANGELOG.md
- Makefile
- hack/release.toml
This is the official v1.5.3 release.
> release(v1.5.3): prepare release

- Makefile
- Pkgfile
- drivers/gasket/vars.yaml
- guest-agents/qemu-guest-agent/glib/pkg.yaml
- guest-agents/qemu-guest-agent/pkg.yaml
- guest-agents/vars.yaml
- guest-agents/xe-guest-utilities/pkg.yaml
- hack/release.toml
- network/tailscale/pkg.yaml
- network/vars.yaml
|---|---|---|
| [https://github.com/qemu/qemu.git](https://togithub.com/qemu/qemu) | patch | `8.1.0` -> `8.1.1` |
| [https://gitlab.gnome.org/GNOME/glib.git](https://gitlab.gnome.org/GNOME/glib) | minor | `2.77.3` -> `2.78.0` |
| [siderolabs/bldr](https://togithub.com/siderolabs/bldr) | patch | `v0.2.1` -> `v0.2.2` |
| [tailscale/tailscale](https://togithub.com/tailscale/tailscale) | minor | `1.48.1` -> `1.50.0` |
| [xenserver/xe-guest-utilities](https://togithub.com/xenserver/xe-guest-utilities) | patch | `8.3.0` -> `8.3.1` |
> feat: update releases

- README.md
- hack/release.toml
Updates the README with stargz-snapshotter
> docs: update README

- CHANGELOG.md
- Makefile
- Pkgfile
This is the official v1.6.0-alpha.1 release.
> release(v1.6.0-alpha.1): prepare release

- .github/workflows/ci.yaml
- .github/workflows/slack-notify.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
See https://github.com/siderolabs/pkgs/pull/828
> feat: update Go to 1.21.4

- CHANGELOG.md
- Makefile
- hack/release.toml
This is the official v1.5.5 release.
> release(v1.5.5): prepare release

- container-runtime/stargz-snapshotter/manifest.yaml
- container-runtime/stargz-snapshotter/stargz-snapshotter.yaml
See https://github.com/siderolabs/talos/pull/7953
> fix: enable rootfs propagation for stargz-snapshotter

- .github/workflows/ci.yaml
- .kres.yaml
- Makefile
- Pkgfile
- container-runtime/stargz-snapshotter/pkg.yaml
- container-runtime/vars.yaml
- guest-agents/qemu-guest-agent/glib/pkg.yaml
- guest-agents/qemu-guest-agent/pkg.yaml
- guest-agents/vars.yaml
- network/tailscale/pkg.yaml
- network/vars.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime-wrapper/go.sum
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.sum
- power/nut-client/patches/replace_system.patch
- power/nut-client/pkg.yaml
- power/vars.yaml
- storage/iscsi-tools/iscsid-wrapper/go.mod
- storage/iscsi-tools/iscsid-wrapper/go.sum
Update pkgs.
|---|---|---|
| [containerd/stargz-snapshotter](https://togithub.com/containerd/stargz-snapshotter) | minor | `v0.14.3` -> `v0.15.1` |
| [https://github.com/qemu/qemu.git](https://togithub.com/qemu/qemu) | patch | `8.1.1` -> `8.1.2` |
| [https://gitlab.gnome.org/GNOME/glib.git](https://gitlab.gnome.org/GNOME/glib) | patch | `2.78.0` -> `2.78.1` |
| [networkupstools/nut](https://togithub.com/networkupstools/nut) | patch | `2.8.0` -> `v2.8.1` |
| [tailscale/tailscale](https://togithub.com/tailscale/tailscale) | minor | `1.50.0` -> `1.54.0` |
> feat: bump dependencies

- CHANGELOG.md
This is the official v1.6.0-alpha.2 release.
> release(v1.6.0-alpha.2): prepare release

- .kres.yaml
- Makefile
Last commit before cutting release-1.6.
> chore: update pkgs to final 1.6.0

- .kres.yaml
- Makefile
- Pkgfile
- hack/release.toml
- storage/zfs/zfs-tools/pkg.yaml
> chore: pull in latest pkgs

- CHANGELOG.md
This is the official v1.6.0-beta.1 release.
> release(v1.6.0-beta.1): prepare release

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- CHANGELOG.md
- Makefile
- hack/release.toml
This is the official v1.6.0 release.
> release(v1.6.0): prepare release

- .kres.yaml
- CHANGELOG.md
- Makefile
- hack/release.toml
This is the official v1.6.1 release.
> release(v1.6.1): prepare release

- .conform.yaml
- .github/workflows/ci.yaml
- .kres.yaml
- Makefile
- Pkgfile
- guest-agents/qemu-guest-agent/qemu-guest-agent.yaml
- hack/release.toml
> chore: updates for Talos 1.6.2

- CHANGELOG.md
- hack/release.toml
This is the official v1.6.2 release.
> release(v1.6.2): prepare release

- .kres.yaml
- Makefile
- Pkgfile
- drivers/chelsio/pkg.yaml
- drivers/gasket/pkg.yaml
- drivers/mellanox-ofed/pkg.yaml
- drivers/thunderbolt/pkg.yaml
- drivers/usb-modem/pkg.yaml
- drivers/v4l-uvc/pkg.yaml
- firmware/amd-ucode/pkg.yaml
- firmware/amdgpu-firmware/pkg.yaml
- firmware/bnx2-bnx2x/pkg.yaml
- firmware/chelsio/pkg.yaml
- firmware/i915-ucode/pkg.yaml
- firmware/intel-ice-firmware/pkg.yaml
- firmware/qlogic-firmware/pkg.yaml
- guest-agents/qemu-guest-agent/glib/pkg.yaml
- guest-agents/qemu-guest-agent/pkg.yaml
- internal/base/pkg.yaml
- misc/binfmt-misc/pkg.yaml
- nvidia-gpu/nonfree/kmod-nvidia/pkg.yaml
- nvidia-gpu/nvidia-modules/pkg.yaml
- power/nut-client/pkg.yaml
- storage/btrfs/pkg.yaml
- storage/drbd/pkg.yaml
- storage/fuse3/pkg.yaml
- storage/iscsi-tools/open-iscsi/pkg.yaml
- storage/iscsi-tools/open-isns/pkg.yaml
- storage/mdadm/pkg.yaml
- storage/zfs/pkg.yaml
Allow to use custom PKGS_PREFIX when building a custom kernel or kernel module
> fix: allow to use custom PKGS_PREFIX

- .kres.yaml
- CHANGELOG.md
- Makefile
- hack/release.toml
This is the official v1.6.3 release.
> release(v1.6.3): prepare release

- nvidia-gpu/nvidia-fabricmanager/pkg.yaml
This fixes fabricmanager crashing.
> fix: set `DATABASE_PATH` for fabricmanager

- .kres.yaml
- CHANGELOG.md
- Makefile
- hack/release.toml
This is the official v1.6.4 release.
> release(v1.6.4): prepare release

- .kres.yaml
- CHANGELOG.md
- Makefile
This is the official v1.7.0-alpha.0 release.
> release(v1.7.0-alpha.0): prepare release

- CHANGELOG.md
- Pkgfile
- hack/release.toml
This is the official v1.5.6 release.
> release(v1.5.6): prepare release

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
- README.md
- container-runtime/vars.yaml
- container-runtime/wasmedge/README.md
- container-runtime/wasmedge/manifest.yaml
- container-runtime/wasmedge/pkg.yaml
- container-runtime/wasmedge/vars.yaml
- container-runtime/wasmedge/wasm.part
> WASM extension

- container-runtime/gvisor/pkg.yaml
- container-runtime/vars.yaml
> feat: update gvisor to 20240212.0

- .kres.yaml
- Makefile
- Pkgfile
- firmware/realtek-firmware/pkg.yaml
- hack/release.toml
Update linux firmware version.
> feat: update pkgs for Talos 1.6.6

- CHANGELOG.md
This is the official v1.6.6 release.
> release(v1.6.6): prepare release

- .kres.yaml
- Pkgfile
- firmware/realtek-firmware/pkg.yaml
- guest-agents/qemu-guest-agent/pkg.yaml
- guest-agents/vars.yaml
- hack/release.toml
- network/tailscale/pkg.yaml
- network/vars.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/elfutils/pkg.yaml
- nvidia-gpu/vars.yaml
|---|---|---|
| git://sourceware.org/git/elfutils.git | minor | `0.190` -> `0.191` |
| [https://github.com/qemu/qemu.git](https://togithub.com/qemu/qemu) | patch | `8.2.1` -> `8.2.2` |
| [tailscale/tailscale](https://togithub.com/tailscale/tailscale) | patch | `1.60.0` -> `1.60.1` |
> feat: update Go to 1.22.1, update releases

- Makefile
- Pkgfile
- guest-agents/qemu-guest-agent/glib/pkg.yaml
- guest-agents/vars.yaml
Fix glib build by disabling elf support.
> fix: glib build

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
- Pkgfile
- container-runtime/gvisor/pkg.yaml
- container-runtime/vars.yaml
- hack/release.toml
Update pkgs, brings in new Linux firmware.
|---|---|---|
| [google/gvisor](https://togithub.com/google/gvisor) | minor | `20240212.0` -> `20240305.0` |
> feat: update dependencies

- CHANGELOG.md
This is the official v1.7.0-alpha.1 release.
> release(v1.7.0-alpha.1): prepare release

- .kres.yaml
- Makefile
Re-enable DRBD extension.
See https://github.com/siderolabs/pkgs/pull/914
> feat: re-enable drbd

- firmware/intel-ucode/pkg.yaml
- firmware/vars.yaml
- hack/release.toml
See
[RFDS](https://www.intel.com/content/www/us/en/developer/articles/technical/software-security-guidance/advisory-guidance/register-file-data-sampling.html).
> feat: update Intel CPU ucode to 20240312

- CHANGELOG.md
This is the official v1.6.7 release.
> release(v1.6.7): prepare release

- .conform.yaml
- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
- container-runtime/gvisor/pkg.yaml
- container-runtime/kata-containers/pkg.yaml
- container-runtime/vars.yaml
- go.work.sum
- network/tailscale/pkg.yaml
- network/vars.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime-wrapper/go.sum
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.sum
- nvidia-gpu/vars.yaml
- power/nut-client/pkg.yaml
- power/vars.yaml
- storage/btrfs/files/modules.txt
- storage/fuse3/pkg.yaml
- storage/iscsi-tools/iscsid-wrapper/go.mod
- storage/iscsi-tools/iscsid-wrapper/go.sum
- storage/vars.yaml
Bump dependencies and bring in stable pkgs.
> chore: bump depedencies

- .kres.yaml
- Makefile
> chore: update Go to 1.22.2

- CHANGELOG.md
This is the official v1.7.0-beta.0 release.
> release(v1.7.0-beta.0): prepare release

- CHANGELOG.md
This is the official v1.7.0-beta.1 release.
> release(v1.7.0-beta.1): prepare release

- .kres.yaml
- Makefile
- Pkgfile
Update linux firmware version.
> chore: update pkgs version to the latest

- .kres.yaml
- Makefile
- Pkgfile
Update Linux firmware version.
> feat: update pkgs to the latest release-1.7

- .conform.yaml
- .drone.yaml
- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
- hack/release.toml
- tools/util-linux/pkg.yaml
> backports: for v1.7.1

- CHANGELOG.md
This is the official v1.7.1 release.
> release(v1.7.1): prepare release

- .kres.yaml
- CHANGELOG.md
- hack/release.toml
This is the official v1.8.0-alpha.0 release.
> release(v1.8.0-alpha.0): prepare release

- .kres.yaml
- Makefile
- Pkgfile
- hack/release.toml
- storage/zfs/zfs-tools/pkg.yaml
see https://github.com/openzfs/zfs/releases/tag/zfs-2.2.4
> feat: update zfs extension to v2.2.4

- firmware/intel-ucode/pkg.yaml
- firmware/vars.yaml
- hack/release.toml
See https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20240514
> feat: update Intel u-code to 20240514

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
- Pkgfile
- drivers/gasket/manifest.yaml
- drivers/usb-modem/manifest.yaml
- drivers/v4l-uvc/manifest.yaml
- firmware/intel-ucode/pkg.yaml
- firmware/vars.yaml
- hack/release.toml
- storage/zfs/zfs-tools/pkg.yaml
> backports: for v1.7.2

- CHANGELOG.md
- hack/release.toml
This is the official v1.7.2 release.
> release(v1.7.2): prepare release

- .kres.yaml
- Makefile
- Pkgfile
- hack/release.toml
> feat: update Linux firmware to 20240513

- CHANGELOG.md
This is the official v1.7.3 release.
> release(v1.7.3): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v1.7.4 release.
> release(v1.7.4): prepare release

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- container-runtime/ecr-credential-provider/pkg.yaml
- container-runtime/gvisor/pkg.yaml
- container-runtime/kata-containers/pkg.yaml
- container-runtime/stargz-snapshotter/pkg.yaml
- examples/hello-world-service/pkg.yaml
- network/tailscale/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime-wrapper/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/pkg.yaml
- storage/iscsi-tools/iscsid-wrapper/pkg.yaml
Add cache paths for go based builds.
> chore: add cache paths for go builds

- network/tailscale/pkg.yaml
- network/vars.yaml
- nvidia-gpu/nvidia-container-toolkit/glibc/pkg.yaml
PR's backported:
* #409 
* #405
> backports: v1.7.5

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
- hack/release.toml
This is the official v1.7.5 release.
> release(v1.7.5): prepare release

- power/nut-client/README.md
Add `upsmonUser` to clarify this is also dependent on the NUT server configuration.
> Improve `nut-client` docs.

- CHANGELOG.md
This is the official v1.8.0-alpha.1 release.
> release(v1.8.0-alpha.1): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v1.6.8 release.
> release(v1.6.8): prepare release

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
- container-runtime/spin/pkg.yaml
- container-runtime/vars.yaml
- hack/release.toml
> backports: for Talos v1.7.6

- hack/release.toml
> chore: no-op change

- CHANGELOG.md
This is the official v1.7.6 release.
> release(v1.7.6): prepare release

- MAINTAINERS.md
- drivers/chelsio/manifest.yaml
- drivers/mellanox-ofed/manifest.yaml
> chore: add MAINTAINERS file

- CHANGELOG.md
This is the official v1.8.0-alpha.2 release.
> release(v1.8.0-alpha.2): prepare release

- CHANGELOG.md
This is the official v1.8.0-beta.0 release.
> release(v1.8.0-beta.0): prepare release

- reproducibility/pkg.yaml
Update pkg names and add missing targets for reproducibility test.
> fix: reproducibility tests

- firmware/intel-ucode/pkg.yaml
- firmware/vars.yaml
- hack/release.toml
See https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20240910
> feat: update Intel u-code to 20240910

- .conform.yaml
- .kres.yaml
- Makefile
- firmware/intel-ucode/pkg.yaml
- firmware/vars.yaml
- hack/release.toml
- disable max of one commit, sync PKGS
- #468
> backports: for v1.8.0-beta.1

- CHANGELOG.md
This is the official v1.8.0-beta.1 release.
> release(v1.8.0-beta.1): prepare release

- .kres.yaml
- Makefile
- Pkgfile
- hack/release.toml
> feat: update pkgs/Linux firmware

- .kres.yaml
- CHANGELOG.md
- Makefile
- hack/release.toml
This is the official v1.8.0 release.
> release(v1.8.0): prepare release

- CHANGELOG.md
This is the official v1.7.7 release.
> release(v1.7.7): prepare release

- .kres.yaml
- Makefile
- hack/release.toml
- storage/mdadm/pkg.yaml
Fix builds with new Talos packages versions
> chore: mdadm, pkgs: update packages and replace eudev by systemd-udevd

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- CHANGELOG.md
- Makefile
- hack/release.toml
This is the official v1.8.1 release.
> release(v1.8.1): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v1.9.0-alpha.0 release.
> release(v1.9.0-alpha.0): prepare release

- storage/mdadm/README.md
Add step by step guide for mdadm related to #489
> feat: Add enhanced step by step guide to create mdadm software raid

- .kres.yaml
- Makefile
- Pkgfile
- hack/release.toml
- storage/iscsi-tools/open-iscsi/patches/login-scan-manual.patch
- storage/iscsi-tools/open-iscsi/pkg.yaml
- storage/iscsi-tools/vars.yaml
* bump pkgs, Linux firmware 
* #500
> backports: for v1.8.2

- .kres.yaml
- CHANGELOG.md
- Makefile
This is the official v1.8.2 release.
> release(v1.8.2): prepare release

- firmware/intel-ucode/pkg.yaml
- firmware/vars.yaml
- hack/release.toml
See https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20241029
> feat: update Intel u-code to 20241029

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- Makefile
- README.md
- reproducibility/pkg.yaml
Add some missing things:
- Add `metal-agent` to README
- Add it to the reproducibility build
- Rekres
> chore: add `metal-agent` into readme and reproducibility, rekres

- CHANGELOG.md
This is the official v1.9.0-alpha.1 release.
> release(v1.9.0-alpha.1): prepare release

- CHANGELOG.md
This is the official v1.9.0-alpha.2 release.
> release(v1.9.0-alpha.2): prepare release

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
- Pkgfile
- hack/release.toml
> feat: update extensions for Linux firmware 20241110

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
- Pkgfile
- firmware/intel-ucode/pkg.yaml
- firmware/vars.yaml
- guest-agents/vars.yaml
- hack/release.toml
- nvidia-gpu/nvidia-fabricmanager/production/lts/pkg.yaml
- nvidia-gpu/vars.yaml
- #508 
- #512 
- #520 
- #510 
- #519
> backports: for v1.8.3

- Makefile
- internal/base/pkg.yaml
Bump extensions validator, also rekres.
> chore: bump extensions validator

- CHANGELOG.md
This is the official v1.8.3 release.
> release(v1.8.3): prepare release

- .github/workflows/ci.yaml
- .github/workflows/slack-notify.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- CHANGELOG.md
- Makefile
This is the official v1.9.0-alpha.3 release.
> release(v1.9.0-alpha.3): prepare release

- .github/workflows/slack-notify.yaml
- .kres.yaml
- Makefile
- Pkgfile
- hack/release.toml
- nvidia-gpu/nvidia-container-toolkit/nvidia-pkgs/lts/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-pkgs/production/pkg.yaml
- nvidia-gpu/nvidia-fabricmanager/lts/pkg.yaml
- nvidia-gpu/nvidia-fabricmanager/production/pkg.yaml
- nvidia-gpu/vars.yaml
- storage/zfs/zfs-tools/pkg.yaml
Matching updates for https://github.com/siderolabs/pkgs/pull/1085
> feat: update Linux to 6.12

- .kres.yaml
- Makefile
- hack/release.toml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/lts/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/production/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime/pkg.yaml
- nvidia-gpu/vars.yaml
Bump NVIDIA toolkit to `v.17.2`.
> chore: bump nvidia toolkit

- nvidia-gpu/nvidia-fabricmanager/production/nvidia-fabricmanager.yaml
Fix NVIDIA FabricManager production.
Fixes: #511
> fix: nvidia fabricmanager production

- storage/zfs/README.md
- currently `talosctl get discoveredvolumes` is used but it's the wrong command
- correct is talosctl mounts
EDIT: closes #539
> [zfs] docs: fix command to show zfs mount

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- CHANGELOG.md
- Makefile
This is the official v1.9.0-beta.1 release.
> release(v1.9.0-beta.1): prepare release

- .github/workflows/ci.yaml
- .github/workflows/slack-notify.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
- firmware/intel-ucode/pkg.yaml
- firmware/vars.yaml
- hack/release.toml
PRs backported: 
- #522 
- update PKGS
> backports: for v1.8.4

- CHANGELOG.md
This is the official v1.8.4 release.
> release(v1.8.4): prepare release

- .github/renovate.json
- .kres.yaml
> chore: rekres for renovate changes

- CHANGELOG.md
- hack/release.toml
This is the official v1.9.0 release.
> release(v1.9.0): prepare release

- drivers/thunderbolt/manifest.yaml
```diff
-Thunderbolg
+Thunderbolt
```
> docs: correct typo

- .kres.yaml
- CHANGELOG.md
- Makefile
This is the official v1.10.0-alpha.0 release.
> release(v1.10.0-alpha.0): prepare release

- CHANGELOG.md
This is the official v1.9.1 release.
> release(v1.9.1): prepare release

- storage/zfs/zfs-tools/pkg.yaml
Fix zfs udev rules installation.
Fixes: #572
> fix: zfs udev rules installation

- CHANGELOG.md
- hack/release.toml
This is the official v1.9.2 release.
> release(v1.9.2): prepare release

- .kres.yaml
- Makefile
- Pkgfile
- container-runtime/ecr-credential-provider/pkg.yaml
- container-runtime/spin/pkg.yaml
- container-runtime/vars.yaml
- hack/release.toml
- misc/glibc/vars.yaml
- network/lldpd/pkg.yaml
- network/vars.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/lts/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/production/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime-wrapper/go.sum
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.sum
- nvidia-gpu/nvidia-container-toolkit/nvidia-pkgs/lts/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-pkgs/production/pkg.yaml
- nvidia-gpu/nvidia-fabricmanager/lts/pkg.yaml
- nvidia-gpu/nvidia-fabricmanager/production/pkg.yaml
- nvidia-gpu/vars.yaml
- storage/zfs/zfs-service/go.mod
- storage/zfs/zfs-service/go.sum
- tools/util-linux/pkg.yaml
* NVIDIA drivers and container toolkit
* spin
* ecr-credential-helper
* wolfi-base
* LLDPD
(cherry picked from commit 70da87510b61ad1a29f22cbdb19dcc30d36e1f91)
> backport: feat: update dependencies

- CHANGELOG.md
This is the official v1.9.3 release.
> release(v1.9.3): prepare release

- .kres.yaml
- Makefile
Preparation for v1.10.0-alpha.1.
> chore: bump pkgs to the latest

- CHANGELOG.md
This is the official v1.10.0-alpha.1 release.
> release(v1.10.0-alpha.1): prepare release

- guest-agents/vars.yaml
- guest-agents/vmtoolsd-guest-agent/pkg.yaml
> feat: update talos-vmtoolsd to v1.0.0

- firmware/intel-ucode/pkg.yaml
- firmware/vars.yaml
- hack/release.toml
See https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20250211
> feat: update Intel u-code to 20250211

- .kres.yaml
- Makefile
- firmware/intel-ucode/pkg.yaml
- firmware/vars.yaml
- guest-agents/metal-agent/metal-agent.yaml
- guest-agents/metal-agent/pkg.yaml
- guest-agents/vars.yaml
- guest-agents/vmtoolsd-guest-agent/pkg.yaml
- hack/release.toml
* #595 
* #601 
* #604 
* #606
> backports: for v1.9.4

- CHANGELOG.md
This is the official v1.9.4 release.
> release(v1.9.4): prepare release

- .kres.yaml
- Makefile
- Pkgfile
- hack/release.toml
- internal/base/pkg.yaml
Also remove ca-certificates dependency, as tools image already includes ca-certificates
Signed-off-by: Dmitry Sharshakov <dmitry.sharshakov@siderolabs.com>
> chore: update pkgs

- .kres.yaml
- Makefile
- firmware/qlogic-firmware/pkg.yaml
See https://github.com/siderolabs/pkgs/pull/1172
See https://github.com/torvalds/linux/blob/7eb172143d5508b4da468ed59ee857c6e5e01da6/drivers/scsi/qla2xxx/Kconfig#L13-L23
> feat: update qlogic firmware for qla2xxx

- .kres.yaml
- Makefile
Prepare for the upcoming release.
> feat: sync kernel version for Talos v1.10.0-alpha.2

- CHANGELOG.md
This is the official v1.10.0-alpha.2 release.
> release(v1.10.0-alpha.2): prepare release

- .kres.yaml
- Makefile
- README.md
- hack/release.toml
- storage/nfsd/files/modules.txt
- storage/nfsd/manifest.yaml
- storage/nfsd/pkg.yaml
- storage/nfsd/vars.yaml
> feat: add nfsd extension

- README.md
Trivial fix to README to fix image link for Nebula extension.
> chore: fix Nebula image link in README

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
- Pkgfile
- firmware/qlogic-firmware/pkg.yaml
> backports: for v1.9.5

- CHANGELOG.md
- hack/release.toml
This is the official v1.9.5 release.
> release(v1.9.5): prepare release

- CHANGELOG.md
This is the official v1.10.0-alpha.3 release.
> release(v1.10.0-alpha.3): prepare release

- .kres.yaml
- MAINTAINERS.md
- Makefile
- README.md
- drm/vc4/files/modules.txt
- drm/vc4/manifest.yaml
- drm/vc4/pkg.yaml
- drm/vc4/vars.yaml
- hack/release.toml
Add vc4 extension.
Requires: https://github.com/siderolabs/pkgs/pull/1196
Relevant issue: https://github.com/siderolabs/extensions/issues/636
> feat: vc4 extension

- .kres.yaml
- MAINTAINERS.md
- Makefile
- README.md
- drivers/xdma-driver/README.md
- drivers/xdma-driver/manifest.yaml
- drivers/xdma-driver/pkg.yaml
- drivers/xdma-driver/vars.yaml
- hack/release.toml
[Companion PR in pkgs](https://github.com/siderolabs/pkgs/pull/1194)
> feat: add Xilinx DMA driver extension

- CHANGELOG.md
This is the official v1.10.0-beta.0 release.
> release(v1.10.0-beta.0): prepare release

- .conform.yaml
- .kres.yaml
- network/tailscale/tailscale.yaml
> backports: for v1.10.0-beta.1

- CHANGELOG.md
This is the official v1.10.0-beta.1 release.
> release(v1.10.0-beta.1): prepare release

- .kres.yaml
- Makefile
- Pkgfile
Update to the latest PKGS, bump `ctr` version.
> feat: update pkgs

- storage/zfs/zfs-tools/libtirpc/patches/sys-queue.h
- storage/zfs/zfs-tools/libtirpc/pkg.yaml
Now https://git.alpinelinux.org/ doesn't allow automated downloads.
> fix: build of tirpc

- .kres.yaml
- Makefile
- Pkgfile
- storage/zfs/zfs-tools/libtirpc/patches/sys-queue.h
- storage/zfs/zfs-tools/libtirpc/pkg.yaml
Update to the latest PKGS, bump `ctr` version.
(cherry picked from commit 6c7422b87573bc3919a75bc4dafe71d6bdf06a62)
PR: #674
> backport: feat: update pkgs

- CHANGELOG.md
- hack/release.toml
This is the official v1.10.0 release.
> release(v1.10.0): prepare release

- .kres.yaml
- Makefile
- Pkgfile
- network/lldpd/patches/sys-queue.h
- network/lldpd/pkg.yaml
- network/tailscale/tailscale.yaml
- storage/zfs/zfs-tools/libtirpc/patches/sys-queue.h
- storage/zfs/zfs-tools/libtirpc/pkg.yaml
- update PKGS
- #669 
- #679 
- #685
> backports: for v1.9.6

- CHANGELOG.md
- hack/release.toml
This is the official v1.10.1 release.
> release(v1.10.1): prepare release

- .kres.yaml
- Makefile
- Pkgfile
- hack/release.toml
Catching up with https://github.com/siderolabs/pkgs/pull/1231.
> feat: update Linux firmware to 20250509

- CHANGELOG.md
- hack/release.toml
This is the official v1.10.2 release.
> release(v1.10.2): prepare release

- .github/renovate.json
- .kres.yaml
- Makefile
- Pkgfile
- container-runtime/ecr-credential-provider/pkg.yaml
- hack/release.toml
- network/tailscale/pkg.yaml
> backports: for v1.10.3

- CHANGELOG.md
This is the official v1.10.3 release.
> release(v1.10.3): prepare release

- guest-agents/vars.yaml
- guest-agents/vmtoolsd-guest-agent/pkg.yaml
- hack/release.toml
This version introduces ARM support
> feat: update vmtoolsd to v1.1.0

- CHANGELOG.md
This is the official v1.11.0-alpha.3 release.
> release(v1.11.0-alpha.3): prepare release

- CHANGELOG.md
This is the official v1.10.5 release.
> release(v1.10.5): prepare release

- hack/release.toml
Copy-paste from Talos to include tools/pkgs changes in the release notes.
> chore: add tools/pkgs in the release notes

- .github/workflows/ci.yaml
- .github/workflows/lock.yml
- .github/workflows/slack-notify.yaml
- .github/workflows/stale.yml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
- Pkgfile
- network/tailscale/pkg.yaml
- nvidia-gpu/nonfree/kmod-nvidia/lts/pkg.yaml
Tailscale is built here, with SBOM generated in its pkg.yaml, and
nvidia-lts copies SBOM from pkgs.
Signed-off-by: Dmitrii Sharshakov <dmitry.sharshakov@siderolabs.com>
> feat: add SBOM to some extensions

- drivers/thunderbolt/README.md
- drivers/thunderbolt/files/99-thunderbolt.rules
- drivers/thunderbolt/manifest.yaml
- drivers/thunderbolt/pkg.yaml
This will authorize devices on system boot
Fixes: https://github.com/siderolabs/extensions/issues/530
> feat: add thunderbolt udev rule

- CHANGELOG.md
This is the official v1.10.6 release.
> release(v1.10.6): prepare release

- dvb/cx23885/pkg.yaml
- dvb/dvb-m88ds3103/pkg.yaml
- firmware/intel-ucode/pkg.yaml
- guest-agents/qemu-guest-agent/pcre2/pkg.yaml
- guest-agents/vmtoolsd-guest-agent/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/libseccomp/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/lts/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/production/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime/pkg.yaml
- power/nut-client/pkg.yaml
- storage/iscsi-tools/open-iscsi/pkg.yaml
- storage/nfsrahead/libevent/pkg.yaml
- storage/nfsrahead/sqlite/pkg.yaml
- storage/zfs/zfs-tools/pkg.yaml
- tools/nvme-cli/libnvme/pkg.yaml
- tools/nvme-cli/pkg.yaml
Status by this PR:
- Has sbom and cpes or purl: `18 files`
- Has sbom, but no cpes/purl: `18 files`
- No sbom: `56 files`
- References source by url: `13 files`
Partial for https://github.com/siderolabs/talos/issues/10940
<details>
```bash
#!/usr/bin/env bash
category_a="_out/sbom.txt"
category_b="_out/sbom-incomplete.txt"
category_c="_out/sbom-missing.txt"
category_d="_out/sbom-missing-has-source.txt"
> "$category_a"
> "$category_b"
> "$category_c"
> "$category_d"
find . -type f -name "pkg.yaml" ! -path "*/internal/*" | while read -r file; do
if grep -qE '^\s*sbom\s*:' "$file"; then
if grep -qE '^\s*(cpes|purl)\s*:' "$file"; then
echo "$file" >> "$category_a"  # Category A
else
echo "$file" >> "$category_b"  # Category B
fi
else
echo "$file" >> "$category_c"      # Category C
if grep -q …
```
> docs: add more extension SBOMs

- dvb/cx23885/pkg.yaml
- dvb/dvb-m88ds3103/pkg.yaml
- guest-agents/qemu-guest-agent/pcre2/pkg.yaml
- storage/zfs/zfs-tools/pkg.yaml
Fixing issues missed from review in #770
> fix: remove sbom of kernel modules

- CHANGELOG.md
- hack/release.toml
This is the official v1.11.0 release.
> release(v1.11.0): prepare release

- .kres.yaml
- Makefile
- README.md
- guest-agents/vars.yaml
- guest-agents/vmtoolsd-guest-agent/manifest.yaml.tmpl
- guest-agents/vmtoolsd-guest-agent/pkg.yaml
- guest-agents/vmtoolsd-guest-agent/talos-vmtoolsd.yaml
- hack/release.toml
- network/zerotier/README.md
- network/zerotier/zerotier-wrapper/main.go
> backports: for v1.11.1

- .github/workflows/ci.yaml
- .github/workflows/grype-scan-cron.yaml
- .kres.yaml
- Makefile
- internal/grype-scan/pkg.yaml
Split out the scan into amd64 and arm64.
> fix: try fixing the grype scan
