- Makefile
- intel-ucode/manifest.yaml
- intel-ucode/pkg.yaml
This PR adds in the ability to install the intel ucode binaries as a
system extension.
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>
> feat: add extension for intel-ucode

- README.md
Specify allowed contents of the `rootfs`.
> docs: update extension spec

- Makefile
- bnx2-bnx2x/manifest.yaml
- bnx2-bnx2x/pkg.yaml
This PR adds bnx2/bnx2x from linux-firmware.
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>
> feat: add broadcom netextreme 2 (bnx2/bnx2x) extension

- Pkgfile
Bump golang to 1.17.7
Ref: https://github.com/talos-systems/tools/pull/168
> chore: bump golang from tools to 1.17.7

- Pkgfile
- nvidia-container-toolkit/DEVELOPMENT.md
- nvidia-container-toolkit/README.md
- nvidia-container-toolkit/manifest.yaml
- nvidia-container-toolkit/nvidia-device-create/15-nvidia-device.rules
- nvidia-container-toolkit/nvidia-device-create/pkg.yaml
- nvidia-container-toolkit/nvidia-pkgs/pkg.yaml
Bump NVIDIA drivers to 510.60.02
Ref: https://github.com/siderolabs/pkgs/pull/434
> chore: bump nvidia drivers to 510.60.02

- Pkgfile
Bump linux-firmware to 20220411
Ref: https://github.com/siderolabs/pkgs/pull/449
> chore: bump linux-firmware to 20220411

- storage/iscsi-tools/iscsid-wrapper/go.mod
- storage/iscsi-tools/iscsid-wrapper/go.sum
- storage/iscsi-tools/iscsid-wrapper/main.go
- storage/iscsi-tools/iscsid-wrapper/pkg.yaml
- storage/iscsi-tools/pkg.yaml
Use `golang.org/x/sys` over deprecated `syscall` package
> chore: use golang.org/x/sys over syscall

- nonfree/nvidia-container-toolkit/nvidia-persistenced-wrapper/main.go
Fix parsing pid files that may contain newlines
It's seen that very rarely the pid file might be created with a newline
and then that would cause the process to restart continuously since we
fail to parse the pid into an integer. Fix by trimming of newlines.
> fix: parsing pidfile with newlines

- README.md
Update extension spec to support glibc standard path.
When needing to run NVIDIA workloads which require tools build around
glibc compiled to a prefix like `/usr/local/glibc`, apps compiled against
glibc had to be invoked as `/usr/local/glibc/lib/ld-linux-x86-64.so.2 <full path to
app>`. Allowing `/lib64/ld-linux-x86-64.so.2` as a allowlist in
extension spec would allow to create a symlink in
`/lib64/ld-linux-x86-64.so.2` which points to
`/usr/local/glibc/lib/ld-linux-x86-64.so.2`.
> chore: update extension spec

- Pkgfile
- nvidia-gpu/nvidia-modules/pkg.yaml
- nvidia-gpu/nvidia-modules/vars.yaml
We'd have to now tag `extensions` with the same version as Talos for
every Talos release.
> fix: nvidia pkg versioning

- Pkgfile
Bump `pkgs` to the version used in [v1.2.0-beta.2](https://github.com/siderolabs/talos/blob/v1.2.0-beta.2/pkg/machinery/gendata/data/pkgs) of Talos.
> release(v1.2.0-beta.2): prepare release

- Makefile
- README.md
- hack/release.toml
- power/nut-client/README.md
- power/nut-client/files/group
- power/nut-client/files/passwd
- power/nut-client/manifest.yaml
- power/nut-client/nut-client.yaml
- power/nut-client/patches/replace_system.patch
- power/nut-client/pkg.yaml
- power/nut-client/vars.yaml
- power/vars.yaml
adds an extensions service, nut-client, that monitors a nut-server for power events and can perform a graceful shutdown when instructed by the nut-server.
tested on 
- nut-client
- Talos v1.2.0
- 3x Lenovo m900 Tiny workstations
- nut-server
- PiKVM
- Cyberpower CP1500PFCLCD
TODO
> feat: add Network UPS Tools client

- Makefile
- README.md
- drivers/gasket/README.md
- drivers/gasket/manifest.yaml
- drivers/gasket/pkg.yaml
- drivers/gasket/vars.yaml
- hack/release.toml
This driver enables the use of [Coral.ai](https://coral.ai/)'s PCIe TPU modules.
Signed-off-by: Branden Cash <203336+ammmze@users.noreply.github.com>
Depends-on: siderolabs/pkgs#580
> feat: add gasket driver

- CHANGELOG.md
- Pkgfile
This is the official v1.3.0-alpha.0 release.
> release(v1.3.0-alpha.0): prepare release

- Pkgfile
- container-runtime/gvisor/pkg.yaml
- container-runtime/vars.yaml
- examples/hello-world-service/src/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.sum
- storage/iscsi-tools/iscsid-wrapper/go.mod
- storage/iscsi-tools/iscsid-wrapper/go.sum
- storage/iscsi-tools/open-iscsi/pkg.yaml
- storage/iscsi-tools/vars.yaml
* minor Go bumps
* gvisor: 20221010.0
* open-iscsi: 2.1.8
> feat: update releases

- Pkgfile
Updates:
* pkgs v1.3.0-alpha.0-33-g8fe5cbc
* Linux firmware 20221012
Signed-off-by: Tim Jones <tim.jones@siderolabs.com>
> chore: update dependencies

- Pkgfile
- container-runtime/gvisor/pkg.yaml
- container-runtime/vars.yaml
- firmware/intel-ucode/pkg.yaml
- firmware/vars.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.sum
- storage/iscsi-tools/iscsid-wrapper/go.mod
- storage/iscsi-tools/iscsid-wrapper/go.sum
- storage/iscsi-tools/open-iscsi/pkg.yaml
* gvisor: 20221107.0
* Linux firmware: 20221109
* Intel ucode: 20221108
> chore: bump dependencies

- Pkgfile
No other release bumps, just preparing for release-1.3 branch.
> feat: bump pkgs to 1.3.0

- hack/release.toml
- storage/iscsi-tools/open-iscsi/pkg.yaml
- storage/iscsi-tools/vars.yaml
Fix iscsi-tools extension by removed files under `/etc` in rootfs.
Fixes: #92
> fix: iscsi-tools extension

- Pkgfile
- power/nut-client/pkg.yaml
- storage/iscsi-tools/open-iscsi/pkg.yaml
Use default symlinks from [base](https://github.com/siderolabs/pkgs/pull/647).
> chore: use default symlinks from base

- Makefile
- drivers/mellanox-ofed/manifest.yaml
- drivers/mellanox-ofed/pkg.yaml
- drivers/mellanox-ofed/vars.yaml
Add Mellanox OFED drivers extension.
Keeping it disabled until it builds with kernel 6.1 Ref: https://github.com/siderolabs/pkgs/pull/661
> feat: add mellanox ofed drivers extension

- .github/renovate.json
Renovate regex doesn't support negative lookaheads. For glibc the tag suffix to always ignore is `9000`, so just match versions that have patch versions matching upto `999`.
> fix: renovate regex

- Makefile
- Pkgfile
- drivers/gasket/pkg.yaml
- drivers/mellanox-ofed/pkg.yaml
- firmware/amd-ucode/pkg.yaml
- firmware/bnx2-bnx2x/pkg.yaml
- firmware/i915-ucode/pkg.yaml
- internal/base/pkg.yaml
- nvidia-gpu/nvidia-modules/pkg.yaml
- power/nut-client/pkg.yaml
- storage/drbd/pkg.yaml
- storage/iscsi-tools/open-iscsi/pkg.yaml
- storage/iscsi-tools/open-isns/pkg.yaml
Make `PKGS_VERSION` a variable to be able to pass from environment.
Also re-enable drbd per https://github.com/siderolabs/pkgs/pull/679
> chore: make `PKGS_VERSION` a variable

- .drone.yaml
Add a promote state for running e2e tests from talos. This would build and push the images and dependency manifest to the local object store path passed from the talos build.
> feat: add drone promote e2e stage

- container-runtime/gvisor/runsc.toml
Gvisor now works on Talos with cgroup support enabled.
Fixes: #4
> chore: re-enable gvisor cgroup support

- .drone.yaml
This PR moves to pushing the manifests to azure instead of our old rook/ceph
> chore: use azure blob storage for builds

- Makefile
This automates image signing process after a release.
> chore: add make targets to automate image signing

- Makefile
This automates image signing process after a release.
(cherry picked from commit c06874c102fe9fc6ceb93a48be77434194f8940c)
> backport: chore: add make targets to automate image signing

- Makefile
Match pkgs version used in Talos v1.4.4
> fix: match pkgs to talos v1.4.4

- Makefile
- README.md
- drivers/usb-modem/README.md
- drivers/usb-modem/manifest.yaml
- drivers/usb-modem/pkg.yaml
- drivers/usb-modem/vars.yaml
- power/nut-client/pkg.yaml
new extension that adds the required drivers to operate usb modems under Talos.
Based on #167
> feat: added usb modem drivers

- Makefile
- README.md
- hack/release.toml
- qemu/qemu-guest-agent/README.md
- qemu/qemu-guest-agent/glib/pkg.yaml
- qemu/qemu-guest-agent/manifest.yaml
- qemu/qemu-guest-agent/pcre2/pkg.yaml
- qemu/qemu-guest-agent/pkg.yaml
- qemu/qemu-guest-agent/qemu-guest-agent.yaml
- qemu/qemu-guest-agent/vars.yaml
- qemu/vars.yaml
I haven't tested this at all yet since I haven't figured out yet what's the best way to do this.
cc @jabbas, since you mentioned this here https://github.com/siderolabs/talos/issues/3630#issuecomment-1399595011.
Try it using:
```yaml
machine:
install:
extensions:
- image: docker.io/reitermarkus/qemu-guest-agent:8.0.2 
```
> Add `qemu-guest-agent` extension.

- CHANGELOG.md
- Makefile
- Pkgfile
- hack/release.toml
This is the official v1.4.6 release.
> release(v1.4.6): prepare release

- power/nut-client/nut-client.yaml
- power/nut-client/patches/replace_system.patch
- power/nut-client/pkg.yaml
Extracted from https://github.com/siderolabs/extensions/pull/173.
> fix: use correct exit status in `nut-client` patch

- power/nut-client/manifest.yaml
- power/nut-client/nut-client.yaml
- qemu/qemu-guest-agent/pkg.yaml
- qemu/qemu-guest-agent/qemu-guest-agent.yaml
Use machined socket for `shutdown`, `poweroff` alias.
Depends on: https://github.com/siderolabs/talos/pull/7489
> chore: use machined for shutdown calls

- README.md
NVIDIA OpenGL/Vulkan files needs to be explicitly in the new locations added.
Ref: https://github.com/NVIDIA/nvidia-container-toolkit/blob/v1.13.5/internal/discover/graphics.go#L83-L89
```bash
root@2f51980391de:/tmp/NVIDIA-Linux-x86_64-535.54.03# find /usr /etc -type f -name "*.json"
/usr/share/glvnd/egl_vendor.d/10_nvidia.json
/usr/share/egl/egl_external_platform.d/10_nvidia_wayland.json
/usr/share/egl/egl_external_platform.d/15_nvidia_gbm.json
/usr/lib/nvidia/egl_dummy_vendor.json
/etc/vulkan/icd.d/nvidia_icd.json
/etc/vulkan/implicit_layer.d/nvidia_layers.json
```
`egl_dummy_vendor.json` can be ignored.
Partial fix for #171
> feat: update extension spec allowlist for opengl

- Makefile
- Pkgfile
- firmware/intel-ucode/pkg.yaml
- firmware/vars.yaml
- network/tailscale/pkg.yaml
- network/vars.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime-wrapper/go.sum
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.sum
- storage/iscsi-tools/iscsid-wrapper/go.mod
- storage/iscsi-tools/iscsid-wrapper/go.sum
AMD ucode (via Linux firmware).
Intel: https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20230808 
Tailscale: 1.46.1
> feat: microcode updates

- drivers/usb-modem/README.md
Fix the wrong module name name in USB modem drivers README.
> docs: fix usb modem readme

- .drone.yaml
- Makefile
- nvidia-gpu/nonfree/kmod-nvidia/files/nvidia.conf
- nvidia-gpu/nonfree/kmod-nvidia/manifest.yaml
- nvidia-gpu/nonfree/kmod-nvidia/pkg.yaml
- nvidia-gpu/nonfree/kmod-nvidia/vars.yaml
At the moment it is kmod-nvidia.
Ref: https://github.com/siderolabs/pkgs/pull/774
Part of: https://github.com/siderolabs/talos/issues/7611
> chore: enable pushing of non-free packages

- Makefile
- nvidia-gpu/nonfree/kmod-nvidia/pkg.yaml
Fix nonfree to refer `-pkg` module.
Currently it was referring itself.
> fix: nonfree nvidia pkg name

- .drone.yaml
- Makefile
- README.md
- storage/btrfs/README.md
- storage/btrfs/manifest.yaml
- storage/btrfs/pkg.yaml
- storage/btrfs/vars.yaml
Part 2 of 2 to add a btrfs extension to talos.
tracking issue: https://github.com/siderolabs/extensions/issues/199
> feat: add btrfs storage extension

- hack/release.toml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime/pkg.yaml
- nvidia-gpu/vars.yaml
Revert nvidia bumps from #220. The extensions-test fail and there's not much debug info available for now.
> chore: revert nvidia bumps from #220

- .drone.yaml
- .gitignore
- Makefile
- internal/extensions/pkg.yaml
Push the list of all images built for a specific version of extension to the `extensions` image. This way one can get a list of versions of extensions compatible with Talos version.
Update `sign-images` step to use `cosign` interactive flow, this is easier. Skip signing already signed images.
> chore: add extensions catalog

- .drone.yaml
- .gitignore
- Makefile
- internal/extensions/pkg.yaml
Push the list of all images built for a specific version of extension to the `extensions` image. This way one can get a list of versions of extensions compatible with Talos version.
Update `sign-images` step to use `cosign` interactive flow, this is easier. Skip signing already signed images.
(cherry picked from commit 8fa50a2fa25f34f38f7bf4f393be0c618f5b8bb7)
> backport: chore: add extensions catalog

- README.md
- container-runtime/gvisor/README.md
- container-runtime/stargz-snapshotter/README.md
- drivers/chelsio/README.md
- drivers/gasket/README.md
- drivers/thunderbolt/README.md
- drivers/usb-modem/README.md
- examples/hello-world-service/README.md
- guest-agents/qemu-guest-agent/README.md
- guest-agents/xe-guest-utilities/README.md
- misc/binfmt-misc/README.md
- network/tailscale/README.md
- nvidia-gpu/nvidia-container-toolkit/README.md
- power/nut-client/README.md
- storage/btrfs/README.md
Remove deprecated `.machine.install.extensions`, point to Talos documentation.
Once Image Factory is live, we can point to it.
> docs: update documentation on installing extensions

- Makefile
- storage/fuse3/manifest.yaml
- storage/fuse3/pkg.yaml
- storage/fuse3/vars.yaml
- storage/vars.yaml
This PR adds an extension for fuse, which allows for the compilation of the fusermount binary. This binary is used by the estargz-snapshotter.
> feat: add fuse3 extension

- container-runtime/stargz-snapshotter/stargz-snapshotter.yaml
This PR updates the stargz extension with mounts needed for fuse to work as expected when deployed alongside the fuse3 extension.
> chore: update stargz extension

- .kres.yaml
- Makefile
- Pkgfile
- hack/release.toml
This brings in DRBD 9.2.6.
See https://github.com/siderolabs/pkgs/pull/831
> chore: update packages

- storage/iscsi-tools/iscsid.yaml
- storage/iscsi-tools/open-iscsi/pkg.yaml
Fixes the `iscsi-tools` install prefix to be `/usr/local`. This broke when moving from `make` to `meson`.
> fix: iscsi-tools install `prefix`

- firmware/intel-ucode/pkg.yaml
- firmware/vars.yaml
- hack/release.toml
Intel released an [out-of-band µcode update](https://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-00950.html) yesterday. This update addresses [CVE-2023-23583](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-23583), also known as [Reptar](https://lock.cmpxchg8b.com/reptar.html), a high severity at-least-DoS which can trigger machine check exceptions from ostensibly privilege separated contexts on processors where `/proc/cpuinfo` shows `flags: fsrm`.
This PR bumps the relevant values in the extensions repo. There appears to be automation here which I wasn't sure how to use, but even if this PR is deficient in some way, I hope it precipitates a new `intel-ucode` release.
> Bump Intel microcode to 20231114 (CVE-2023-23583)

- .github/workflows/ci.yaml
- .kres.yaml
Push the `extensions` image, this was missed when the CI was moved from drone to GitHub actions.
> fix: extensions image push was missed

- .kres.yaml
- Makefile
- storage/zfs/zfs-tools/pkg.yaml
This fixes the zfs extension to remove the `no-op` file which depends on the host having a shell.
> fix: zfs extension

- .github/workflows/ci.yaml
- .kres.yaml
- Makefile
- extensions.yaml
Get all extensions manifests from all subfolders and put them into a single file to help with the scenario when it's necessary to read all possible extensions information.
> feat: generate a single extensions information file for all extensions

- .gitignore
- .kres.yaml
- Makefile
- internal/extensions/pkg.yaml
Add all authors and descriptions to the `descriptions.yaml` file, then add this file to the published `extensions` docker image.
Signed-off-by: Artem Chernyshev <artem.chernyshev@talos-systems.com>
(cherry picked from commit 57503ccd3bbba510401dbde67340b71eee0adfee)
> backport: feat: generate extensions descriptions file as part of extensions image

- guest-agents/qemu-guest-agent/qemu-guest-agent.yaml
Allows qemu-ga to run under maintenance mode.
Resolves: #293
> fix: qemu-guest-agent not starting in maintenance mode.

- tools/util-linux/pkg.yaml
The version was bumped in the previous change, but the SHAs weren't updated properly.
> fix: update SHAs for util-linux

- nvidia-gpu/nvidia-fabricmanager/pkg.yaml
This fixes fabricmanager crashing.
(cherry picked from commit 799a3403eab2e28baed1e44063c1851d72215eee)
> fix: set `DATABASE_PATH` for fabricmanager

- network/tailscale/README.md
- network/tailscale/tailscale.yaml
- power/nut-client/README.md
- power/nut-client/nut-client.yaml
Use `ExtensionServiceConfig` document for extensions using `.machine.files` or `environmentFile`.
Ref: https://github.com/siderolabs/talos/pull/8273
> feat: use `ExtensionServiceConfig` document.

- CHANGELOG.md
- hack/release.toml
This is the official v1.6.5 release.
> release(v1.6.5): prepare release

- storage/mdadm/pkg.yaml
In Intel VROC setups, maintaining the integrity of imsm metadata is essential. mdmon plays a pivotal role in ensuring the efficiency of metadata management. Our PR incorporates mdmon into the directory alongside mdadm. This integration guarantees proper functionality in Intel VROC environments
> feat: add mdmon to mdadm extension

- .drone.yaml
We only build for Talos integration tests, and resource allocation works very bad when promoted from a Talos pipeline.
> chore: drop Drone requests for resources

- .kres.yaml
- Makefile
- guest-agents/talos-vmtoolsd/pkg.yaml
- hack/release.toml
Fix the name used for vmtools, as it was conflicting with the container image name in talos-vmtoolds repo.
> fix: vmtoolsd extension name

- .drone.yaml
We only test extensions with amd64 machines, this allows us to get rid of the beefy CI arm64 node used with drone.
> ci: chore only build amd64 for extensions e2e

- tools/util-linux/pkg.yaml
It always showed `$VERSION` as the installed version.
> fix: version in util-linux manifest

- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- Makefile
I forgot to do that, and 1.8.0-alpha.0 release is now out of sync with Talos.
I will re-do the release.
> fix: rekres the repo after pkgs bump

- README.md
- tools/util-linux/pkg.yaml
PR just includes `nsenter` in the subset of built binaries when compiling `util-linux`. Specifically, having `nsenter` allows several common tools written in golang to run on Talos.
> feat: include `nsenter` when building util-linux binaries

- container-runtime/gvisor-debug/pkg.yaml
Fix gvisor-debug extension, got broken when adding extensions-validator.
> fix: gvisor-debug extension

- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/elfutils/pkg.yaml
- storage/zfs/zfs-tools/libtirpc/pkg.yaml
- storage/zfs/zfs-tools/pkg.yaml
Use a custom path for libtirpc shipped with zfs-tools so that it doesn't conflict with libtirpc built for nvidia-container-toolkit (as it's linked against glibc).
Fixes: #380
> fix: zfs-tools libtirpc path

- .kres.yaml
- Makefile
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/elfutils/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/libcap2/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/libseccomp/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/libtirpc/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/zlib/pkg.yaml
- storage/zfs/zfs-tools/libtirpc/pkg.yaml
- storage/zfs/zfs-tools/pkg.yaml
Introduce a proper fix for #401, keep musl path's as is, and use `/usr/local/glibc` as install path for all glibc related stuff so that any new common libraries will not cause an issue in the future.
> fix: zfs extensions with nvidia

- storage/iscsi-tools/tgtd.yaml
- storage/zfs/zpool-importer.yaml
We don't need these proc mounts anymore, also having them `rshared` causes weird issues with volume discovery.
> chore: drop `/proc` mounts.

- network/tailscale/pkg.yaml
- network/vars.yaml
To mitigate security vulnerability:
https://tailscale.com/security-bulletins#ts-2024-005
in release branches
> chore: bump tailscale to v1.68.1

- nvidia-gpu/nvidia-container-toolkit/glibc/ld.so.conf
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-pkgs/pkg.yaml
Set `glibc/lib` as first `rpath` for `nvidia-container-cli`. Also install nvidia libraries to `/usr/local/glibc/lib` so any musl libraries lives separately.
`nvidia-container-cli` explicitly sets an `RPATH` as `$ORIGIN/../$LIB` here: https://gitlab.com/nvidia/container-toolkit/libnvidia-container/-/blob/v1.14.6/Makefile?ref_type=tags#L183, this means `/usr/local/lib` would be searched first, since `zfs` and nvidia ship their own `libtirpc`, `nvidia-container-cli` first tries to use the `libtirpc` shippeed with `zfs` at `/usr/local/lib` instead of the one at `/usr/local/glibc/lib`. Fix this by setting an additional `RPATH` as `$ORIGIN/../glibc/$LIB`, so that libraries in `/usr/local/glibc/lib` have higher preference.
```bash
❯ scanelf -r …
```
> fix: glibc search paths for nvidia

- container-runtime/gvisor/README.md
- container-runtime/gvisor/gvisor-kvm.part
- container-runtime/gvisor/pkg.yaml
- container-runtime/gvisor/runsc-kvm.toml
This patch adds a new runtime class to the gvisor extension allowing to
use the KVM platform feature. This is done by selecting `runsc-kvm` as
runtime.
> feat(gvisor): Add new runtime class with KVM support

- container-runtime/gvisor/gvisor-kvm.part
- container-runtime/gvisor/gvisor.part
- container-runtime/kata-containers/kata-containers.part
- container-runtime/spin/spin.part
- container-runtime/stargz-snapshotter/stargz-snapshotter.part
- container-runtime/wasmedge/wasm.part
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime/nvidia-container-runtime.part
The CRI plugin name got changed.
See https://github.com/siderolabs/talos/pull/9078
> fix: update CRI config parts for containerd config v3

- .github/renovate.json
- Makefile
- container-runtime/crun/README.md
- container-runtime/crun/crun.part
- container-runtime/crun/manifest.yaml
- container-runtime/crun/pkg.yaml
- container-runtime/crun/vars.yaml
- container-runtime/vars.yaml
**About:**
This adds the [crun](https://github.com/containers/crun) container runtime-class to talos sytsem extentions.  
crun is a alternative implementation of the container-runtime-interface (cri) written in C.
It claims to 50% faster but the difference I conduced by a recent performance comparison between different cri's was 21% faster runc and it required less memory making it a great choice for low end and embedded systems.
**Tests:**
I created my own talos system image for the hetzner cloud (for amd64 & arm64) and created a cluster with this extension. With the RuntimeClass for crun applied I was able to create container just like the defualt runc cri.
For a quick test the vm-images assets in [this](https://github.com/hegerdes/helper-suite/releases/tag/v2024.07.01) GitHub release …
> feat: add crun container-runtime extension

- .kres.yaml
- Makefile
- Pkgfile
- container-runtime/ecr-credential-provider/pkg.yaml
- container-runtime/gvisor/pkg.yaml
- container-runtime/spin/pkg.yaml
- container-runtime/vars.yaml
- examples/hello-world-service/src/go.mod
- guest-agents/qemu-guest-agent/glib/pkg.yaml
- guest-agents/qemu-guest-agent/pkg.yaml
- guest-agents/vars.yaml
- hack/release.toml
- network/tailscale/pkg.yaml
- network/vars.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime-wrapper/go.sum
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.sum
- storage/iscsi-tools/iscsid-wrapper/go.mod
- storage/iscsi-tools/iscsid-wrapper/go.sum
- tools/util-linux/pkg.yaml
- run rekres
- siderolabs/pkgs to v1.8.0-alpha.0-41-ga97d58f
- golang.org/x/sys to v0.23.0
- linux firmware to 20240709
- google/gvisor to 20240729.0
- cloud-provider-aws to v1.30.3
- containerd-shim-spin to v0.15.1
- kata-containers/kata-containers to 3.7.0
- qemu to 9.0.2
- glib to 2.81.1
- siderolabs/talos-vmtoolsd to v0.6.0
- tailscale/tailscale to 1.70.0
> chore: bump deps

- container-runtime/stargz-snapshotter/stargz-snapshotter.yaml
This PR adds the default root path parameter to *stargz-snapshotter* extension as an argument: `--root`. It sets the path to */var/lib/containerd/io.containerd.snapshotter.v1.stargz* as it is a more common place to find it. The snapshotter default path is defined in [stargz-snapshotter/cmd/containerd-stargz-grpc/main.go#L66](https://github.com/containerd/stargz-snapshotter/blob/1dac5ef893199b3617e6a6cd118d75d71adc7df1/cmd/containerd-stargz-grpc/main.go#L66) and points to */var/lib/containerd-stargz-grpc*.
When trying the *stargz-snapshotter* extension I found some errors and seemed that the snapshotter wasn't working properly. I didn't copy the errors but they were something in the lines of:
- missing directory */var/lib/containerd/io.containerd.snapshotter.v1.stargz*.
- …
> fix(stargz-snapshotter): set default root path

- .dockerignore
- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
- Pkgfile
- container-runtime/crun/pkg.yaml
- container-runtime/ecr-credential-provider/pkg.yaml
- container-runtime/vars.yaml
- firmware/intel-ucode/pkg.yaml
- firmware/vars.yaml
- guest-agents/qemu-guest-agent/glib/pkg.yaml
- hack/release.sh
- hack/release.toml
- network/tailscale/pkg.yaml
- network/vars.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime-wrapper/go.sum
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.sum
- nvidia-gpu/vars.yaml
- storage/iscsi-tools/iscsid-wrapper/go.mod
- storage/iscsi-tools/iscsid-wrapper/go.sum
Rekres, bump Go deps.
|---|---|---|
| [containers/crun](https://togithub.com/containers/crun) | patch | `1.16` -> `1.16.1` |
| [intel/Intel-Linux-Processor-Microcode-Data-Files](https://togithub.com/intel/Intel-Linux-Processor-Microcode-Data-Files) | minor | `20240531` -> `20240813` |
| [kubernetes/cloud-provider-aws](https://togithub.com/kubernetes/cloud-provider-aws) | minor | `v1.30.3` -> `v1.31.0` |
| [tailscale/tailscale](https://togithub.com/tailscale/tailscale) | minor | `1.70.0` -> `1.72.1` |
| cgr.dev/chainguard/wolfi-base |  digest | `bf0547b` -> `72c8bfe` |
> feat: bump dependencies

- .kres.yaml
- Makefile
- Pkgfile
- container-runtime/gvisor/pkg.yaml
- container-runtime/vars.yaml
- guest-agents/qemu-guest-agent/glib/pkg.yaml
- guest-agents/qemu-guest-agent/pkg.yaml
- guest-agents/vars.yaml
- hack/release.toml
- storage/zfs/zfs-tools/pkg.yaml
Update `pkgs` to Talos 1.8.0 version.
ZFS to 2.2.6 via pkgs.
|---|---|---|
| [google/gvisor](https://redirect.github.com/google/gvisor) | minor | `20240729.0` -> `20240826.0` |
| [https://github.com/qemu/qemu.git](https://redirect.github.com/qemu/qemu) | minor | `9.0.2` -> `9.1.0` |
| [https://gitlab.gnome.org/GNOME/glib.git](https://gitlab.gnome.org/GNOME/glib) | minor | `2.81.1` -> `2.82.0` |
> feat: update depenendencies

- container-runtime/crun/pkg.yaml
- container-runtime/gvisor/pkg.yaml
- container-runtime/kata-containers/pkg.yaml
- container-runtime/spin/pkg.yaml
- container-runtime/stargz-snapshotter/pkg.yaml
- examples/hello-world-service/pkg.yaml
- guest-agents/qemu-guest-agent/pkg.yaml
- guest-agents/xen-guest-agent/pkg.yaml
- network/tailscale/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/lts/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/production/pkg.yaml
- nvidia-gpu/nvidia-fabricmanager/lts/pkg.yaml
- nvidia-gpu/nvidia-fabricmanager/production/lts/pkg.yaml
- power/nut-client/pkg.yaml
- storage/iscsi-tools/pkg.yaml
- storage/zfs/pkg.yaml
See https://github.com/tonistiigi/fsutil/issues/207
The result of this issue is that we can't use `finalize` steps where destination is a directory, so refactor things to pull in such steps into the `install` step.
> fix: image reproducibility with finalize

- storage/zfs/pkg.yaml
When refactoring, I put the wrong path for the extension service file.
> fix: put zfs extensions service yaml to proper path

- .kres.yaml
- Makefile
- Pkgfile
- container-runtime/crun/pkg.yaml
- container-runtime/gvisor/pkg.yaml
- container-runtime/kata-containers/pkg.yaml
- container-runtime/spin/pkg.yaml
- container-runtime/stargz-snapshotter/pkg.yaml
- examples/hello-world-service/pkg.yaml
- guest-agents/qemu-guest-agent/pkg.yaml
- guest-agents/xen-guest-agent/pkg.yaml
- hack/release.toml
- network/tailscale/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/lts/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/production/pkg.yaml
- nvidia-gpu/nvidia-fabricmanager/lts/pkg.yaml
- nvidia-gpu/nvidia-fabricmanager/production/lts/pkg.yaml
- power/nut-client/pkg.yaml
- storage/iscsi-tools/pkg.yaml
- storage/zfs/pkg.yaml
> backports: for v1.8.0

- .kres.yaml
- Makefile
- README.md
- internal/base/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-pkgs/lts/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-pkgs/production/pkg.yaml
- power/nut-client/pkg.yaml
- storage/iscsi-tools/open-iscsi/pkg.yaml
- storage/mdadm/pkg.yaml
- storage/zfs/zfs-tools/pkg.yaml
Ref: siderolabs/pkgs#1053
Signed-off-by: Dmitry Sharshakov <dmitry.sharshakov@siderolabs.com>
> chore: move udev rules

- misc/glibc/vars.yaml
- nvidia-gpu/vars.yaml
Fix the glibc extension build by updating wolfi-base. The wolfi repo has a new build of python3 that depends on an updated libssl from the base image.
The content hash was retrieved from cgr.dev/chainguard/wolfi-base:latest on 2024-11-01T17:50:00-07:00.
> chore: update wolfi-base

- nvidia-gpu/nvidia-fabricmanager/production/lts/pkg.yaml
Include all topology files from the Nvidia fabric manager release.
This will help ensure compatibility with newer GPU architectures, and fixes the issue of not including files required for H100 and H200
> feat(fabricmanager): add all topology files

- .kres.yaml
- MAINTAINERS.md
- Makefile
- guest-agents/metal-agent/README.md
- guest-agents/metal-agent/manifest.yaml
- guest-agents/metal-agent/metal-agent.yaml
- guest-agents/metal-agent/pkg.yaml
- guest-agents/metal-agent/vars.yaml
- guest-agents/vars.yaml
Add the new metal agent extension to run Talos in metal agent mode.
Related to https://github.com/siderolabs/talos/pull/9501.
Depends on https://github.com/siderolabs/talos-metal-agent/pull/1 and the initial release (`v0.1.0`) of the agent.
> feat: add extension `metal-agent`

- storage/zfs/manifest.yaml
- storage/zfs/pkg.yaml
- storage/zfs/zfs-service.yaml
- storage/zfs/zfs-service/go.mod
- storage/zfs/zfs-service/go.sum
- storage/zfs/zfs-service/main.go
- storage/zfs/zfs-service/pkg.yaml
This patch adds a new service to the zfs extension (`zfs-service`) that handles pool import and unmount. These operations are tied to the service lifecycle: the service imports all pools when it starts, waits for an exit signal, then unmounts all pools before exiting.
As a subtle additional benefit, the service passes the `-l` flag to `zpool-import`[^1], which instructs it to request encryption keys for all encrypted datasets. Using the zfs `keylocation`[^2] property and Talos secure boot and TPM disk encryption, a ZFS encryption key file can be safely stored on the EPHEMERAL partition to import encrypted datasets at boot. Alternatively, a key can be stored on an https server.
[^1]: https://openzfs.github.io/openzfs-docs/man/master/8/zpool-import.8.html
[^2]: …
> feat: add zfs-service to zfs extension (unmount, encryption)

- guest-agents/vars.yaml
- hack/release.toml
Bump the version to 0.6.1 to add the latest bugfix version of vmtoolsd to Talos extensions.
[https://github.com/siderolabs/talos-vmtoolsd/releases/tag/v0.6.1](https://github.com/siderolabs/talos-vmtoolsd/releases/tag/v0.6.1)
> bump vmtoolsd version to v0.6.1

- firmware/intel-ucode/pkg.yaml
- firmware/vars.yaml
- hack/release.toml
See https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20241112
> feat: update Intel u-code to 20241112

- guest-agents/vars.yaml
Bump it to v0.1.0-alpha.2: https://github.com/siderolabs/talos-metal-agent/releases/tag/v0.1.0-alpha.2
> chore: bump metal-agent

- guest-agents/metal-agent/metal-agent.yaml
Set the common paths in the PATH variable, so that we don't need to hardcode the `ipmitool` path.
> feat: set PATH variable in metal-agent

- guest-agents/vars.yaml
Bump metal agent version.
https://github.com/siderolabs/talos-metal-agent/releases/tag/v0.1.0-beta.0
> chore: bump metal agent version

- network/cloudflared/manifest.yaml
- network/cloudflared/pkg.yaml
- reproducibility/pkg.yaml
Hi, here are the changes linked to this PR https://github.com/siderolabs/extensions/pull/542, to put the binaries back rather than building from the sources.
By the way, I don't understand why you changed the version variable names ([in your commit of the previous PR](https://github.com/siderolabs/extensions/commit/1dd6c364b8aae54a891ef1b371417e4b6b263030)) from ‘.VERSION’ to ‘.CLOUDFALRED_VERSION’. In the end, in the manifest.yaml, you end up replacing some variables with ‘.CLOUDFLARED_VERSION’ and leaves others with ‘.VERSION’, which isn't clear or consistent.
I've replaced everything with ‘.CLOUDFLARED_VERSION’, and deleted the vars.yml file containing the ‘.VERSION’ vars, which is now useless.
Finally, could you remove the current ghcr.io/siderolabs/cloudflared:2024.12.1 image, which …
> fix: used cloudflared binaries instead of building from sources

- .kres.yaml
- Makefile
- drivers/mei/files/modules.txt
I am not able to do hardware transcoding with an intel 14th gen CPU and noticed this in dmesg.
```
[drm] GT1: can't init GSC proxy due to missing mei component
```
https://github.com/torvalds/linux/blob/master/drivers/misc/mei/gsc_proxy/Kconfig
Related: https://github.com/siderolabs/pkgs/pull/1116
> fix: add `gsc_proxy/mei_gsc_proxy` to mei modules

- nvidia-gpu/nvidia-fabricmanager/production/nvidia-fabricmanager.yaml
- nvidia-gpu/nvidia-fabricmanager/production/pkg.yaml
This contains a proper fix for #511 and reverts commit b452bc66b8bc70826a6f737f0fd021119c778562.
> Fix: nvidia-fabricmanager production

- .github/renovate.json
- .github/workflows/ci.yaml
- .github/workflows/weekly.yaml
- .kres.yaml
- Makefile
- Pkgfile
- drivers/thunderbolt/manifest.yaml
- hack/release.toml
> backports: for v1.9.1

- .github/renovate.json
- .kres.yaml
- Makefile
- Pkgfile
- container-runtime/ecr-credential-provider/pkg.yaml
- container-runtime/spin/pkg.yaml
- container-runtime/vars.yaml
- hack/release.toml
- misc/glibc/vars.yaml
- network/lldpd/pkg.yaml
- network/vars.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/lts/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/production/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime-wrapper/go.sum
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.mod
- nvidia-gpu/nvidia-container-toolkit/nvidia-persistenced-wrapper/go.sum
- nvidia-gpu/nvidia-container-toolkit/nvidia-pkgs/lts/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-pkgs/production/pkg.yaml
- nvidia-gpu/nvidia-fabricmanager/lts/pkg.yaml
- nvidia-gpu/nvidia-fabricmanager/production/pkg.yaml
- nvidia-gpu/vars.yaml
- storage/zfs/zfs-service/go.mod
- storage/zfs/zfs-service/go.sum
- storage/zfs/zfs-tools/pkg.yaml
- tools/util-linux/pkg.yaml
* NVIDIA drivers and container toolkit
* spin
* ecr-credential-helper
* wolfi-base
* LLDPD
> feat: update dependencies

- guest-agents/metal-agent/metal-agent.yaml
- guest-agents/metal-agent/pkg.yaml
- guest-agents/vars.yaml
Instead of copying ca certs from its image, mount them from the host into the agent container. This way, agent can also use additional ca certificates added via `TrustedRootsConfig` config documents.
Also bump the agent version to `v0.1.0`.
> feat: mount host ca certs into metal agent

- guest-agents/metal-agent/pkg.yaml
- guest-agents/vars.yaml
Since we switch to native IPMI implementation in Go, we don't need to shell out to ipmitool. Remove it and its dependencies.
See https://github.com/siderolabs/talos-metal-agent/releases/tag/v0.1.2.
Part of https://github.com/siderolabs/omni/issues/896.
> feat: bump metal agent to v0.1.2

- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/lts/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/production/pkg.yaml
- nvidia-gpu/nvidia-container-toolkit/nvidia-container-runtime/pkg.yaml
Pin Go version to 1.23 for NVIDIA tools, since upstream doesn't build with Go 1.24 without patches.
> fix: pin go version to 1.23 for nvidia tools

- guest-agents/vmtoolsd-guest-agent/pkg.yaml
- guest-agents/vmtoolsd-guest-agent/stub-manifest.yaml
Empty extension image for arm64 makes imager fail on arm64, and specifically Image Factory when generating arm64 image.
See https://github.com/siderolabs/talos/issues/1037
> fix: use proper stub for vmtoolsd on arm64

- guest-agents/vmtoolsd-guest-agent/pkg.yaml
- guest-agents/vmtoolsd-guest-agent/stub-manifest.yaml
Empty extension image for arm64 makes imager fail on arm64, and specifically Image Factory when generating arm64 image.
(cherry picked from commit aa141a6a7539c99c3f3f3c7116644167033fa1f7)
> backport: fix: use proper stub for vmtoolsd on arm64

- container-runtime/kata-containers/pkg.yaml
I was reviewing pkg.yml file and noticed a few lines that appear to be duplicated. Specifically, the following block is repeated:
```bash
cp ./opt/kata/bin/cloud-hypervisor /rootfs/usr/local/bin/cloud-hypervisor
chmod +x /rootfs/usr/local/bin/cloud-hypervisor
```
Let me know. If this makes sense, I’d be happy to assist with the update.
Thanks for your hard work on this
> chore: remove duplicate lines

- network/lldpd/README.md
Fix command recognition issue: change `lldpd` to `lldp`
https://github.com/siderolabs/extensions/tree/main/network/lldpd
```
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: lldpd
configFiles:
- content: |
configure lldpd <-[**  HERE   **] portidsubtype ifname
unconfigure lldp management-addresses-advertisements
unconfigure lldp capabilities-advertisements
```
This PR fixes a command recognition issue in `lldpd` extension. Previously, using `lldpd` as a command argument resulted in an unknown command error. According to the [official documentation](https://lldpd.github.io/usage.html), the correct command should be `lldp`.
Before the fix, executing the command produced the following warning:
```
x.x.x.x: 2025-02-19T03:01:31 [WARN/lldpctl] unknown command from argument 2: `lldpd` …
```
> Correct typo in lldpd extension

- .kres.yaml
- MAINTAINERS.md
- Makefile
- README.md
- drm/panfrost/files/modules.txt
- drm/panfrost/manifest.yaml
- drm/panfrost/pkg.yaml
- drm/panfrost/vars.yaml
This extension loads the panfrost module for arm mali midgard & birfrost gpus used by various sbcs. I've compiled the extension the _out folder only had the manifest.yaml and the bldr file this seemed the same as the amd gpu drm module so i'm thinking this is correct. Also is there anything else I need to do to add this to image factory or this it pick this up automatically once merged? Also updated the makefile with the kernel build that has the panfrost module.
> feat: add extenstion for panfrost module

- .kres.yaml
- Makefile
This is a no-op change, as it matches the previous tag, but to get things into proper shape before upcoming 1.10.0-beta.0 release.
> chore: update pkgs to final 1.10.0 tag

- CHANGELOG.md
This is the official v1.11.0-alpha.0 release.
> release(v1.11.0-alpha.0): prepare release

- CHANGELOG.md
- hack/release.toml
This is the official v1.9.6 release.
> release(v1.9.6): prepare release

- drm/panfrost/files/modules.txt
- drm/panfrost/manifest.yaml
This PR adds panthor module in panfrost extension to support Valhall GPUs
> feat(panfrost): include panthor kernel module

- .kres.yaml
- Makefile
- storage/btrfs/files/modules.txt
With https://github.com/siderolabs/pkgs/pull/1228, the zstd is no longer a module, but part of the kernel.
> chore: update pkgs and zstd module

- .github/renovate.json
- .kres.yaml
- Makefile
- Pkgfile
- drivers/tenstorrent/README.md
- drivers/tenstorrent/manifest.yaml
- drivers/tenstorrent/pkg.yaml
- drivers/tenstorrent/vars.yaml
- hack/release.toml
Using tenstorrent package for kernel module
> feat: add tenstorrent extension

- container-runtime/ecr-credential-provider/pkg.yaml
The bump to v1.33 changed the binary to be dynamically linked. Explicitly set `CGO_ENABLED=0` while building.
Fixes: #706
> fix: staticallty link ecr-credential-provider

- network/tailscale/pkg.yaml
Moving to new toolchain meant we didn't set `CGO_ENABLED=0` from bldr anymore. Explicitly set it.
> fix: tailscale static builds

- misc/glibc/ld.so.conf
- misc/glibc/pkg.yaml
This patch changes the glibc extension to use the `lib64` directory for libraries instead of `lib`. This better reflects a standard Fedora/FHS/LSB distribution and fixes issues with a few containers, with the Nvidia Linux installer, and with the Nvidia container toolkit.
The Nvidia container toolkit mounts libraries at the same path as the host system and runs `ldconfig` to update the cache. Mounting 64-bit libraries in `lib` is wrong on Fedora-like _and_ Ubuntu-like distributions.
> fix(glibc): use lib64 for better compatibility

- internal/base/pkg.yaml
- network/nebula/nebula.yaml
The spec was missing the `mounts` key.
Fixes: https://github.com/siderolabs/talos/discussions/11108
> fix: nebula extension spec

- internal/base/pkg.yaml
- network/nebula/nebula.yaml
The spec was missing the `mounts` key.
Fixes: https://github.com/siderolabs/talos/discussions/11108
(cherry picked from commit 1efc06bf0e22817e336ceb16c5328b204653c357)
> backport: fix: nebula extension spec

- network/newt/newt.yaml
This was an oversight from me. I didn't test it with a secure endpoint when I wrote that extension.
It fixes errors like this in the extension's logs.
```log
talos.example.ca: ERROR: 2025/07/04 16:33:50 Failed to connect: failed to get token: failed to request new token: Post "https://pangolin.example.ca/api/v1/auth/newt/get-token": tls: failed to verify certificate: x509: certificate signed by unknown authority. Retrying in 10s...
```
It is based on the work done on Tailscale in #669 which fixed #665.
I figured Tailscale was a good example since it needs to reach a public endpoint that's of course using secure connections too.
> fix: TLS Verification failures on Newt

- storage/nfsrahead/pkg.yaml
Upstream has the `99-nfs.rules` artifact already built, so we need to run a `make clean` to delete this file and recreate it with the correct prefix: `/usr/local`. Otherwise, the udev rule will never work because it's pointing to this binary `/usr/libexec/nfsrahead` instead of the generated one `/usr/local/libexec/nfsrahead`
+ https://github.com/siderolabs/extensions/commit/c479d91284a4f98236306d6efce1ab8a46d43a74
> fix: nfsrahead udev rule

- network/zerotier/README.md
- network/zerotier/zerotier-wrapper/main.go
Add custom plant file for zerotier
Forked from #799
> feat: zerotier - add possible custom planet file

- nvidia-gpu/nvidia-container-toolkit/nvidia-container-cli/libtirpc/pkg.yaml
Make sure it's always updated.
Signed-off-by: Dmitrii Sharshakov <dmitry.sharshakov@siderolabs.com>
> fix: nvidia-container-toolkit: use SHA512 from a variable for tirpc

- CHANGELOG.md
- hack/release.toml
This is the official v1.12.0-alpha.0 release.
> release(v1.12.0-alpha.0): prepare release

- .github/workflows/ci.yaml
- .github/workflows/grype-scan-cron.yaml
- .github/workflows/stale.yml
- .github/workflows/weekly.yaml
- README.md
- guest-agents/vars.yaml
- hack/release.toml
This version ignores a privilege error when running with secure boot.
See https://github.com/siderolabs/talos-vmtoolsd/releases/tag/v1.4.0.
> feat: update vmtoolsd to v1.4.0
